### ISSUE TITLE
Missing Mountain Time Zone [BUG]

### ISSUE THREAD

**Issue by thekug** [microsoft/Edge-Device-Image-Builder-Public-Preview#1]
Time Zone for Mountain Time (UTC -07:00) is not present in the drop down when selecting the locale information about the image build
![image](https://user-images.githubusercontent.com/35356510/170567106-179f1917-4efe-4940-9319-78c023c1ab19.png)

This issue appears on EDIB v0.3.3 public preview, running on Windows 11 21H2 22000.675

**Comment by rsameser** [comment]
Will close once the issue has been resolved.

**Comment by rsameser** [comment]
This issue has been resolved, please check out the latest build: https://aka.ms/EDIBPublicPreviewRelease
