### ISSUE TITLE
Windows Update Policy Auto-Restart: Checkbox Logic

### ISSUE THREAD

**Issue by thekug** [microsoft/Edge-Device-Image-Builder-Public-Preview#2]
Confusing logic around the `Turn off auto-restart for updates during active hours` section. When the Turn Off (disable) Auto-Restart check box is enabled, the Active Hours text boxes become inactive and do not apply any longer as the Auto-Restart will not occur. If I am understanding this correctly, when the checkbox is unchecked, the Active Hours text boxes should now be enabled to control when the enabled auto-restart will happen.

![image](https://user-images.githubusercontent.com/35356510/170570426-4d845b8f-760f-4381-baae-2e1f9e877b3c.png)

![image](https://user-images.githubusercontent.com/35356510/170570475-dfe9297a-d8d3-4dce-bf50-c811b14764cd.png)

**Comment by rsameser** [comment]
Thanks for your feedback here! We will review and see how we can make this a more user-friendly experience.

**Comment by rsameser** [comment]
Please review the following documentation to further understand how this feature was configured: 

- https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/edib/edib-windows-update?view=windows-11
- https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart#configure-active-hours
