### ISSUE TITLE
Building custom Windows Container base images from host OS and/or .ISO

### ISSUE THREAD

**Issue by ohault** [microsoft/Edge-Device-Image-Builder-Public-Preview#3]
For use cases where transparency requirements prohibit the use of undocumented official Windows container base images provided by Microsoft, or specific needs not met by these images.

**Comment by rsameser** [comment]
Please reach out to your Windows IoT Distributor (http://aka.ms/iotdistributorlist) to acquire the Windows IoT Enterprise OPK. 

This is a part of the pre-requisites needed to leverage this tool: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/edib/edib-configure-the-environment?view=windows-11#how-to-tell-youre-using-the-right-isos

**Comment by ohault** [comment]
Hi @rsameser, can you please ré-open this ticket, because I'm targeting here Windows Container base images. What is currently not supported. Thanks
