### ISSUE TITLE
Build fails when we add updates to be included as part from building image

### ISSUE THREAD

**Issue by sandyshek** [microsoft/Edge-Device-Image-Builder-Public-Preview#5]
PowerShell error: Add-WindowsPackage : An error occurred applying the Unattend.xml file from the .msu package.

==> Some builds didn't complete successfully and had errors:
--> wim: error installing LCU C:/Users/chands50/Downloads/Updates/windows10.0-kb5008876-x64-ndp48_5a565d73e211e26a8bb51bc19a7689ac01eb4cad.msu: PowerShell error: Add-WindowsPackage : An error occurred applying the Unattend.xml file from the .msu package.
For more information, review the log file.
At C:\Users\chands50\AppData\Local\Temp\powershell305426536.ps1:1 char:1

**Comment by rsameser** [comment]
This is a known issue - please review the following documentation: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/edib/edib-add-apps?view=windows-11 

Only Win32 apps with silent or unattended installation options are supported. App installers that require manual interaction will cause build failures.
