### ISSUE TITLE
Build error when VC ++ redistributables are added in tool as part of prerequisites

### ISSUE THREAD

**Issue by sandyshek** [microsoft/Edge-Device-Image-Builder-Public-Preview#6]
==> hyperv-iso: Installing provisioning package...
==> hyperv-iso: Install-ProvisioningPackage : Process 'C:\Windows\System32\provtool.exe' with args
==> hyperv-iso: '"e:\ppkg\win32driver-vcredist_x64.ppkg" /quiet /source PSCmdlet' took longer than '180000' milli-sec
==> hyperv-iso: At line:1 char:1
==> hyperv-iso: + Install-ProvisioningPackage -PackagePath e:\ppkg\win32driver-vcredist ...
==> hyperv-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> hyperv-iso:     + CategoryInfo          : NotSpecified: (:) [Install-ProvisioningPackage], CmdletException
==> hyperv-iso:     + FullyQualifiedErrorId : -2146233088 (80131500),Microsoft.Windows.Provisioning.ProvUtils.Commands.InstallProvisio
==> hyperv-iso:    ningPackage
==> hyperv-iso:
==> hyperv-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> hyperv-iso: Clean up secondary dvd drives...
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting build directory...
Build 'hyperv-iso' errored after 10 minutes 2 seconds: Installation of provisioning package failed: 1
==> Wait completed after 10 minutes 2 seconds
==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: Installation of provisioning package failed: 1
==> Builds finished but no artifacts were created.
[ImageBuilder]: Error occurred: 
STACKTRACE:    at Microsoft.ImageBuilder.Common.ExternalProcess.WaitForExit()
   at Microsoft.ImageBuilder.API.ImageBuilder.RunPacker(String template, String errorBehavior)
   at Microsoft.ImageBuilder.API.ImageBuilder.<>c__DisplayClass13_0.<Build>b__2()
   at Microsoft.ImageBuilder.API.ImageActionBase.RunStagedStep(Action action, Stage stage)
   at Microsoft.ImageBuilder.API.ImageActionBase.RunStagedStep(Action action, Stage stage, CancellationTokenSource cancelSrc)
   at Microsoft.ImageBuilder.API.ImageBuilder.Build(ImageConfiguration imageConfig, TargetImage targetImage, String uiVersion, String sessionID)
EXCEPTION: 
	 C:\temp\win\2022-08-17T10_10_53.852+05_30\Build\packer.exe failed with exit code=1.

**Comment by rsameser** [comment]
This is a known issue - please review the following documentation: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/edib/edib-add-apps?view=windows-11 

Only Win32 apps with silent or unattended installation options are supported. App installers that require manual interaction will cause build failures.
